/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee;

import admin.AdminProfile;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.EmpDetails;

/**
 *
 * @author Dheerendra
 */
public class ChangeEmpPwd extends javax.swing.JFrame {

    /**
     * Creates new form ChangeEmpPwd
     */
    EmpDetails ed;
    public ChangeEmpPwd(EmpDetails ed) {
        initComponents();
        this.ed=ed;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(910, 580));
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("DK MART"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("CHANGE YOUR PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(285, 67, 335, 48);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("E-MAIL ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(164, 189, 62, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("OLD PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(125, 285, 101, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("NEW PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(123, 362, 103, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("CONFIRM NEW PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(63, 450, 163, 15);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(304, 176, 325, 43);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("CHANGE PASSWORD");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 470, 240, 63);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(304, 259, 325, 41);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(304, 348, 325, 45);
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(304, 437, 325, 43);

        jButton2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 14)); // NOI18N
        jButton2.setText("<---");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 0, 70, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password1.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 950, 600);

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
              String email=jTextField1.getText();
              char [] oldpass=jPasswordField1.getPassword();
              String oldpass1=new String(oldpass);
              char[] newpass=jPasswordField2.getPassword();
              String newpass1=new String(newpass);
              char[] cnfpass=jPasswordField3.getPassword();
              String cnfpass1=new String(cnfpass);
              
              
              if(email.equals(""))
              {
                  JOptionPane.showMessageDialog(rootPane, "Enter email id","ERROR",JOptionPane.ERROR_MESSAGE);
              }
              else if(oldpass1.equals(""))
              {
                  JOptionPane.showMessageDialog(rootPane, "Enter old password","ERROR",JOptionPane.ERROR_MESSAGE);
              }
              else if(newpass1.equals(""))
              {
                  JOptionPane.showMessageDialog(rootPane, "Enter new password","ERROR",JOptionPane.ERROR_MESSAGE);
              }
              else if(cnfpass1.equals(""))
              {
                  JOptionPane.showMessageDialog(rootPane, "Confirm new password","ERROR",JOptionPane.ERROR_MESSAGE);
              }
              else
              {
              try 
                  (
                    Connection con=dbconnection.dbConnection.getConnect();
                    PreparedStatement ps=con.prepareStatement("select * from register where email='"+email+"'and password ='"+oldpass1+"'");
                      ResultSet rs=ps.executeQuery();
                  )
              {
                    if(rs.next())
                    {
                        if(newpass1.equals(cnfpass1))
                        {
                            try 
                                
                             (
                               Connection con1=dbconnection.dbConnection.getConnect();
                               PreparedStatement ps1=con1.prepareStatement("update register set password='"+newpass1+"'where email='"+email+"'");
                               
                               )
                            {
                                int i=ps1.executeUpdate();
                                if(i>0)
                                {
                                    JOptionPane.showMessageDialog(rootPane, "password changed sucessfully");
                                    EmpProfile ep=new EmpProfile(ed);
                                    ep.setVisible(true);
                                    setVisible(false);
                                }
                                else 
                                {
                                    JOptionPane.showMessageDialog(rootPane, "password didnt changed","ERROR",JOptionPane.ERROR_MESSAGE);
                                }
                            }
                            catch (Exception e) 
                            {
                                e.printStackTrace();
                            }
                        }
                        else
                        {
                         JOptionPane.showMessageDialog(rootPane,"new password didnt matched","ERROR",JOptionPane.ERROR_MESSAGE);
                        }
                    }
                        else
                        {
                           JOptionPane.showMessageDialog(rootPane, "old password didnt matched","ERROR",JOptionPane.ERROR_MESSAGE);
                        }
              } 
              catch (Exception e) 
              {
                  e.printStackTrace();
              }
              }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EmpProfile ep=new EmpProfile(ed);
        ep.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeEmpPwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeEmpPwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeEmpPwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeEmpPwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeEmpPwd(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
