/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.ir.ContinueNode;

/**
 *
 * @author Dheerendra
 */
public class EditItems extends javax.swing.JFrame {

  String itemid;
  File file;
 
    public EditItems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 595));
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("DK MART"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 14)); // NOI18N
        jButton1.setText("<---");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 70, 27);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Item Id", "Item Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(19, 59, 383, 460);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(449, 118, 235, 34);

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(449, 196, 235, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select category", "mens wear", "ladies wear", "kids wear (boy)", "kids wear (girl)", " " }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(449, 269, 235, 38);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(449, 355, 235, 94);

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(449, 497, 235, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select image.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(767, 59, 195, 248);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Select Image");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(795, 325, 147, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("UPDATE");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(795, 404, 147, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("UPDATE ITEM DETAILS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(359, 11, 280, 34);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ITEM NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(449, 98, 70, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("PRICE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(449, 176, 40, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("CATEGORY");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(449, 249, 70, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("DESCREPTION");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(449, 335, 90, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("QUANTITY");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(449, 477, 70, 15);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edititem1.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1000, 560);

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        AdminProfile ap=new AdminProfile();
        ap.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        
        String item_id,item_name;
        int srno=0;
        try 
            (
                 Connection con=dbconnection.dbConnection.getConnect();
                PreparedStatement ps=con.prepareStatement("select * from items");
                ResultSet rs= ps.executeQuery();
            )
        {
            while(rs.next())
            {
                srno++;
                item_id= rs.getString("item_id");
                item_name=rs.getString("item_name");
                Object[] o={srno,item_id,item_name};
                dtm.addRow(o);
            }
        }
        catch (Exception e) 
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        int row=jTable1.getSelectedRow();
        itemid=(String)jTable1.getValueAt(row, 1);
        
        String itemname,itemprice,itemcategory,itemqnty,itemdesc;
        
          try 
            (
                 Connection con=dbconnection.dbConnection.getConnect();
                PreparedStatement ps=con.prepareStatement("select * from items where item_id='"+itemid+"'");
                ResultSet rs= ps.executeQuery();
            )
        {
            while(rs.next())
            {
              itemname=rs.getString("item_name");
              itemprice=rs.getString("price");
              itemcategory=rs.getString("category");
              itemqnty=rs.getString("quantity");
              itemdesc=rs.getString("descreption");
               BufferedImage im = ImageIO.read(rs.getBinaryStream("image"));
               jLabel1.setIcon(new ImageIcon(im.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),Image.SCALE_DEFAULT)));
              
              jTextArea1.setText(itemdesc);
              jTextField1.setText(itemname);
              jTextField2.setText(itemprice);
              jTextField3.setText(itemqnty);
              jComboBox1.setSelectedItem(itemcategory);
              
            }
        }
        catch (Exception e) 
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         
        String name=jTextField1.getText();
        String price=jTextField2.getText();
        String category=(String)jComboBox1.getSelectedItem();
        String desc=jTextArea1.getText();
        String quantity=jTextField3.getText();
        String idE=itemid;
        
         FileInputStream fis = null;
        
         if(file !=null)
         {
              try 
        {
             fis=new FileInputStream(file);
        }
        catch (IOException e) 
        {
            e.printStackTrace();
        }
         }
       
        if(fis !=null)
        {
        try 
            (
               Connection con=dbconnection.dbConnection.getConnect();
               PreparedStatement ps=con.prepareStatement("update items set item_name=?,price=?,quantity=?,descreption=?,category=?,image=? where item_id=?");
               
            )
        {
            ps.setString(1, name);
            ps.setString(2, price);
            ps.setString(3,quantity);
            ps.setString(4, desc);
            ps.setString(5, category);
            ps.setBinaryStream(6,fis,file.length());
            ps.setString(7, itemid);
            int i=ps.executeUpdate();
            
            if(i>0)
            {
                JOptionPane.showMessageDialog(rootPane, "successfull");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "error");
            }
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
     }
        else
        {
              try 
            (
               Connection con=dbconnection.dbConnection.getConnect();
               PreparedStatement ps=con.prepareStatement("update items set item_name=?,price=?,quantity=?,descreption=?,category=? where item_id=?");
               
            )
        {
            ps.setString(1, name);
            ps.setString(2, price);
            ps.setString(3,quantity);
            ps.setString(4, desc);
            ps.setString(5, category);
            ps.setString(6, itemid);
            int i=ps.executeUpdate();
            
            if(i>0)
            {
                JOptionPane.showMessageDialog(rootPane, "successfull");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "error");
            }
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
        }
    
        int i=jTable1.getSelectedRow();
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        if(i>0)
        {
        dtm.setValueAt(name, i, 2);
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"try again");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        JFileChooser fileChooser=new JFileChooser();
        fileChooser.showOpenDialog(rootPane);
        file=fileChooser.getSelectedFile();
       
             ImageIcon imageIcon = new ImageIcon(new ImageIcon(file.getAbsolutePath()).getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
             jLabel1.setIcon(imageIcon);
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
